import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — GrowthOS",
  description: "The terms that govern your use of GrowthOS.",
};

// Source: docs/plans/terms-of-service.md (Dave's draft), reconciled against shipped reality —
// notably: §3's future pricing table collapsed to the live early-access truth (canonical pricing
// lives on /pricing), AI attribution corrected to the Anthropic + Cloudflare split, and Google
// sign-in added. Governing law is deliberately deferred until a legal entity exists.
export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" effectiveDate="July 19, 2026">
      <section>
        <h2>1. What GrowthOS is</h2>
        <p>
          GrowthOS is an AI-driven growth planning platform. You describe a business goal; AI
          agents research channels (subreddits, communities, publications, platforms) and generate
          a structured campaign — Goal, Channels, Plans, and Todos — including draft marketing
          copy, images, and tool recommendations. GrowthOS plans and drafts;{" "}
          <strong>it never publishes or posts anything on your behalf.</strong>
        </p>
        <p>
          Some free tools — the homepage preview and the Subreddit Finder — work without an
          account and carry their own daily usage limits. These terms apply to them too.
        </p>
      </section>

      <section>
        <h2>2. Accounts</h2>
        <ul>
          <li>
            You need an account to create and manage campaigns — email/password or Google
            sign-in, via Supabase Auth.
          </li>
          <li>
            You&apos;re responsible for activity under your account and for keeping credentials
            secure.
          </li>
          <li>One account per user unless a future paid plan explicitly grants additional seats.</li>
        </ul>
      </section>

      <section>
        <h2>3. Pricing &amp; usage limits</h2>
        <p>
          GrowthOS is currently in <strong>free early access</strong> — there is no billing in the
          product and nothing here can charge you. Planned paid tiers are described on the{" "}
          <Link href="/pricing" className="text-primary hover:underline">
            pricing page
          </Link>
          , which is the canonical source for current plans and limits; billing terms take effect
          only when paid plans actually ship, with notice.
        </p>
        <p>
          To keep early access free for everyone, AI actions are subject to fair usage limits: a
          monthly allowance of AI credits (each action's cost and your remaining balance are shown
          in Settings) plus daily caps, surfaced in-product when you reach them. Attempting to
          circumvent these limits is a violation of these terms.
        </p>
      </section>

      <section>
        <h2>4. AI-generated content</h2>
        <ul>
          <li>
            Campaigns, todos, copy drafts, and images are generated by AI models from{" "}
            <strong>Anthropic</strong> (Claude, including live web search for channel research and
            launch timing) and <strong>Cloudflare Workers AI</strong> (open models including Llama
            for most generation, and FLUX for images).
          </li>
          <li>
            AI output can be wrong, outdated, or unsuitable for a given community&apos;s rules.
            You are responsible for reviewing and editing anything before you publish or send it.
          </li>
          <li>
            Our copywriting agents carry guardrails against fabricating metrics, faking
            testimonials, and hiding that you built your product — but you remain responsible for
            what you actually publish.
          </li>
          <li>
            You own the campaigns and content you create. You grant GrowthOS the right to process
            your inputs solely to provide the service — generate, store, and display them to you.
          </li>
        </ul>
      </section>

      <section>
        <h2>5. Acceptable use</h2>
        <p>Don&apos;t use GrowthOS to:</p>
        <ul>
          <li>
            Generate spam, harassment, or content that violates the rules of the platform or
            community you post to.
          </li>
          <li>
            Present AI-generated claims as independently verified fact — fabricated metrics and
            fake testimonials are exactly what this product is built to prevent.
          </li>
          <li>
            Circumvent usage limits (including with multiple accounts), reverse-engineer the
            service, or resell access without authorization.
          </li>
          <li>Upload content you don&apos;t have the rights to use.</li>
        </ul>
        <p>We may suspend or terminate accounts that violate this section.</p>
      </section>

      <section>
        <h2>6. Third-party services</h2>
        <p>
          GrowthOS runs on third-party infrastructure — Anthropic and Cloudflare (AI), Supabase
          (auth, database, storage), Resend (email delivery), and Vercel (hosting). Outages or
          changes in these providers can affect availability. See the{" "}
          <Link href="/privacy" className="text-primary hover:underline">
            Privacy Policy
          </Link>{" "}
          for how your data flows through them.
        </p>
      </section>

      <section>
        <h2>7. Availability &amp; changes</h2>
        <ul>
          <li>
            GrowthOS is under active development; features and limits may change. Material changes
            to any future paid plan will be communicated in advance.
          </li>
          <li>
            We don&apos;t guarantee uninterrupted availability. The service is provided &ldquo;as
            is&rdquo; without warranty of any kind, to the extent permitted by law.
          </li>
        </ul>
      </section>

      <section>
        <h2>8. Limitation of liability</h2>
        <p>
          To the extent permitted by law, GrowthOS is not liable for indirect, incidental, or
          consequential damages — including harm from publishing AI-generated content without
          review, third-party platform bans, or lost profits. Our total liability for any claim is
          capped at the amount you paid us in the 12 months before the claim.
        </p>
      </section>

      <section>
        <h2>9. Termination</h2>
        <p>
          You can stop using GrowthOS at any time (see the Privacy Policy for account deletion).
          We may suspend or terminate accounts for violating these terms or abusing the AI agents
          — for example, automated generation intended to evade usage limits.
        </p>
      </section>

      <section>
        <h2>10. Governing law &amp; changes to these terms</h2>
        <p>
          A governing jurisdiction will be designated when GrowthOS formalizes as a legal entity;
          these terms will be updated at that point. We may update these terms as the product
          evolves — continued use after an update constitutes acceptance, and material changes get
          a new effective date at the top of this page.
        </p>
      </section>
    </LegalPage>
  );
}
